### ISSUE TITLE
issue('Platform 1 does not exist.') coming on yarn seed

### ISSUE THREAD

**Issue by dsrawat984** [stelace/heroes-platform-demo#450]
Hi Team,

I am getting this below error when I run the **yarn seed** in hero-platform-demo deployment. 

```bash:~/marketplace-demo$ yarn seed
yarn run v1.22.10
$ node scripts/init-data.js
{
  message: 'Internal Server Error',
  statusCode: 500,
  _stack: [
    'Error: Platform 1 does not exist.',
    '    at getPlatformEnvData (/home/ubuntu/stelace/src/redis.js:191:24)',
    '    at runMicrotasks (<anonymous>)',
    '    at processTicksAndRejections (internal/process/task_queues.js:94:5)',
    '    at async getConnection (/home/ubuntu/stelace/src/models/index.js:96:28)',
    '    at async getModels (/home/ubuntu/stelace/src/models/index.js:142:34)',
    '    at async /home/ubuntu/stelace/src/services/apiKey.js:453:24',
    '    at async newHandler (/home/ubuntu/stelace/src/cote/CustomResponder.js:33:24)'
  ],
  _message: 'Platform 1 does not exist.'
}
```

Thank you

**Comment by abruere** [comment]
Hi, did not see your issue sorry.
Closing before archiving this project but `yarn seed` must be run from server-side https://github.com/stelace/stelace.
This project is a simple front-end demo.
